parameters:
- name: name
  type: string
- name: display_name
  type: string
- name: condition
  type: boolean
  default: true
- name: artifact_name
  type: string
- name: environment
  type: string
  default: Docker Registry
- name: image_name
  type: string
- name: container_registry
  type: string
- name: dll_name
  type: string
- name: target_framework
  type: string
  default: net9.0
  values:
  - net5.0
  - net6.0
  - net7.0
  - net8.0
  - net9.0
- name: migration_bundle
  type: boolean
  default: true

jobs:
  - deployment: ${{parameters.name}}
    displayName: '${{parameters.display_name}}'
    environment: ${{parameters.environment}}
    condition: and(succeeded(), ${{parameters.condition}})
    variables:
      - name: image_version
        value:  ${{ replace(parameters.target_framework, 'net', '') }}-alpine
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'templates'
            path: 'templates'

          - task: ExtractFiles@1
            name: extract_artifact
            displayName: 'Extract artifact'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/**/*.zip'
              destinationFolder: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/deploy'
              cleanDestinationFolder: true
              overwriteExistingFiles: true

          - template: /azure/steps/version/get.yml@templates
            parameters:
              dll_path: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/deploy/${{parameters.dll_name}}'

          - task: replacetokens@6
            name: replace_dockerfile
            displayName: 'Replace dockerfile'
            inputs:
              root: '$(Pipeline.Workspace)/templates/azure/dockerfiles'
              sources: '*.Dockerfile'
              additionalVariables: |
                DLL_NAME: ${{parameters.dll_name}}
                IMAGE_VERSION: ${{variables.image_version}}
              useAdditionalVariablesOnly: true
              ifNoFilesFound: 'error'
              missingVarLog: 'error'

          - task: Docker@2
            name: build
            displayName: 'Build image'
            inputs:
              containerRegistry: ${{ parameters.container_registry }}
              repository: ${{ parameters.image_name }}
              command: 'build'
              Dockerfile: '$(Pipeline.Workspace)/templates/azure/dockerfiles/csharp.Dockerfile'
              buildContext: $(Pipeline.Workspace)/${{parameters.artifact_name}}/deploy
              tags: $(get_version.version)
              addPipelineData: false
              addBaseImageData: false
          
          - task: Docker@2
            name: build_migration
            displayName: 'Build migration image'
            inputs:
              containerRegistry: ${{ parameters.container_registry }}
              repository: ${{ parameters.image_name }}
              command: 'build'
              Dockerfile: '$(Pipeline.Workspace)/templates/azure/dockerfiles/migration.Dockerfile'
              buildContext: $(Pipeline.Workspace)/${{parameters.artifact_name}}
              tags: $(get_version.version_migration)
              addPipelineData: false
              addBaseImageData: false

          - task: Docker@2
            name: push
            displayName: 'Push image'
            inputs:
              containerRegistry: ${{ parameters.container_registry }}
              repository: ${{ parameters.image_name }}
              command: 'push'
              tags: $(get_version.version) $(get_version.version_migration)