parameters:
- name: artifact_name
  type: string
  default: 'artifact'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - calculate_sem_version
  - build_package
- name: environments
  type: object
  default: 
  - Production
- name: nuget_api_key
  type: string
  default: $(NUGET_API_KEY)
- name: nuget_source_url
  type: string
  default: https://api.nuget.org/v3/index.json

stages:
- stage: package_publish
  displayName: 'Publish package'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  condition: |
    and(
      succeeded(),
      eq(dependencies.calculate_sem_version.outputs['calculate_version.staging_deploy'], true)
    )
  jobs:
  - ${{ each environment in parameters.environments }}:
    - deployment: package_publish_${{environment}}
      environment: ${{environment}}
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: |
                ls $(Pipeline.Workspace)/**/*$(Build.BuildNumber).nupkg | xargs -L3 dotnet nuget push -k ${{ parameters.nuget_api_key }} -s ${{ parameters.nuget_source_url }}
              displayName: 'Push to Nuget'
              name: nuget_push