parameters:
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - image_publish
- name: environments
  type: object
  default: 
  - Production
- name: image_name
  type: string
- name: digital_ocean_file_spec_path
  type: string
  default: '.devops/digitalocean_spec.yml'
- name: digital_ocean_api_token
  type: string
  default: $(DIGITAL_OCEAN_API_TOKEN)

stages:
- stage: digital_ocean_deploy
  displayName: 'Digital Ocean App Deploy'
  variables:
  - name: VERSION
    value: $(Build.BuildNumber)
  - name: DIGITAL_OCEAN_SPEC_FILE
    value: $[combine('$(Pipeline.Workspace)/project/', '${{ parameters.digital_ocean_file_spec_path }}')]
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  condition: succeeded()
  jobs:
  - ${{ each environment in parameters.environments }}:
    - deployment: digital_ocean_deployment
      displayName: 'Deploy to DigitalOcean'
      environment: ${{environment}}
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: 'self'
              path: 'project'

            - checkout: 'templates'
              path: 'templates'

            - task: DigitalOceanDoctlInstaller@2
              name: deploy_install_doctl
              displayName: 'Install Doctl'

            - task: replacetokens@5
              name: deploy_replace_tokens
              displayName: 'Prepare Spec file'
              inputs:
                rootDirectory: '.'
                targetFiles: ${{ variables.DIGITAL_OCEAN_SPEC_FILE }}
                encoding: 'auto'
                tokenPattern: 'default'
                writeBOM: true
                actionOnMissing: fail
                keepToken: false
                actionOnNoFiles: fail
                enableTransforms: false
                useLegacyPattern: false
                enableTelemetry: true

            - task: DigitalOceanDoctl@2
              displayName: 'Publish app'
              inputs:
                arguments: 'apps create -t ${{ parameters.digital_ocean_api_token }} --spec ${{ variables.DIGITAL_OCEAN_SPEC_FILE }} --upsert true'