parameters:
- name: artifact_name
  type: string
  default: 'artifact'
- name: projects
  type: string
  default: 'src/**/*.csproj'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - calculate_sem_version
- name: version
  type: string
  default: $(Build.BuildNumber)
- name: sonar_organization
  type: string
  default: $(SONAR_ORGANIZATION)
- name: sonar_project_key
  type: string
  default: $(SONAR_PROJECTKEY)
- name: target_framework
  type: string
  default: net6.0
  values:
  - net5.0
  - net6.0
  - net7.0
  - net8.0
- name: run_tests
  type: boolean
  default: true
- name: run_sonar
  type: boolean
  default: true
- name: install_new_relic
  type: boolean
  default: true

stages:
- stage: build_app
  displayName: 'App Build'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  jobs:
  - job: build
    displayName: 'Build app'
    condition: succeeded()
    variables:
      version: ${{parameters.version}}
    steps:
    - checkout: self
      path: 'project'

    - checkout: 'templates'
      path: 'templates'

    - ${{ if eq(parameters.run_sonar, true) }}:
      - script: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk -y
          JAVA_HOME_CONTENT='export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
          export PATH="$JAVA_HOME/bin:$PATH"'
          
          echo "$JAVA_HOME_CONTENT" | sudo tee /etc/profile.d/java_home.sh > /dev/null
          
          sudo chmod +x /etc/profile.d/java_home.sh
          
          source /etc/profile
        displayName: 'Install Java'

      - task: Bash@3
        displayName: Install Sonar Scanner
        name: sonar_install
        inputs:
          targetType: 'inline'
          workingDirectory: '$(Pipeline.Workspace)/project'
          script: |
            dotnet tool update dotnet-sonarscanner --tool-path tools --ignore-failed-sources

      - task: Bash@3
        displayName: Begin Sonar Scanner
        name: sonar_begin
        inputs:
          targetType: 'inline'
          workingDirectory: '$(Pipeline.Workspace)/project'
          script: |
            ./tools/dotnet-sonarscanner begin \
              /k:$SONAR_PROJECT_KEY \
              /o:$SONAR_PROJECT_ORGANIZATION \
              /v:$VERSION\
              /d:sonar.token=$SONAR_TOKEN \
              /d:sonar.host.url=$SONAR_URL \
              /d:sonar.dotnet.excludeTestProjects=true \
              /d:sonar.cs.opencover.reportsPaths=$(Pipeline.Workspace)/project/test*/*/TestResults/*/coverage.opencover.xml \
              /d:sonar.java.jdkHome=$JAVA_HOME
        env:
          SONAR_PROJECT_KEY: ${{parameters.sonar_project_key}}
          SONAR_PROJECT_ORGANIZATION: ${{parameters.sonar_organization}}
          SONAR_TOKEN: ${{parameters.sonar_token}}
          SONAR_URL: ${{parameters.sonar_url}}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    - ${{ if eq(parameters.install_new_relic, true) }}:
      - task: DotNetCoreCLI@2
        displayName: 'Add NewRelic'
        inputs:
          command: 'custom'
          projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'
          custom: 'add'
          arguments: 'package NewRelic.Agent'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'
        arguments: '--no-incremental --no-restore --configuration Release'

    - ${{ if eq(parameters.run_tests, true) }}:
      - task: Bash@3
        displayName: Run tests with coverage
        name: coverage_run
        inputs:
          targetType: 'inline'
          workingDirectory: '$(Pipeline.Workspace)/project'
          script: |
            dotnet test --no-restore --no-build --configuration Release --collect:"XPlat Code Coverage" --settings $(Pipeline.Workspace)/templates/coverlet/coverlet.runsettings --logger trx

      - task: PublishCodeCoverageResults@2
        inputs:
          summaryFileLocation: $(Pipeline.Workspace)/project/test*/*/TestResults/*/coverage.opencover.xml
          pathToSources: $(Pipeline.Workspace)/project/src/
        displayName: Publish coverage
    
    - ${{ if eq(parameters.run_sonar, true) }}:
      - task: Bash@3
        displayName: End Sonar Scanner
        name: sonar_end
        inputs:
          targetType: 'inline'
          workingDirectory: '$(Pipeline.Workspace)/project'
          script: |
            ./tools/dotnet-sonarscanner end \
              /d:sonar.token=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{parameters.sonar_token}}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  
    
    - task: DotNetCoreCLI@2
      displayName: Publish for ${{ parameters.target_framework }}
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'
        arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/${{ parameters.target_framework }} -f ${{ parameters.target_framework }}'
        zipAfterPublish: true
        modifyOutputPath: true
        configuration: 'Release'
        versioningScheme: byEnvVar
        versionEnvVar: version

    - task: PublishPipelineArtifact@1
      displayName: Store Application Artifact
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'
        artifact: '${{parameters.artifact_name}}'
