parameters:
- name: artifact_name
  type: string
  default: 'artifact'
- name: projects
  type: string
  default: 'src/**/*.csproj'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - calculate_sem_version
- name: version
  type: string
  default: $(Build.BuildNumber)
- name: sonar_organization
  type: string
  default: $(SONAR_ORGANIZATION)
- name: sonar_project_key
  type: string
  default: $(SONAR_PROJECTKEY)
- name: sonar_token
  type: string
  default: $(SONAR_TOKEN)
- name: sonar_service
  type: string
  default: 'SonarCloud'
- name: run_tests
  type: boolean
  default: true
- name: run_sonar
  type: boolean
  default: true
- name: target_frameworks
  type: object
  default:
    - '5.x'
    - '6.x'
    - '7.x'
    - '8.x'
    - '9.x'
  values:
    - '5.x'
    - '6.x'
    - '7.x'
    - '8.x'
    - '9.x'

stages:
- stage: build_package
  displayName: 'Package Build'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  jobs:
  - job: build
    displayName: 'Build package'
    condition: succeeded()
    variables:
      version: ${{parameters.version}}
    steps:
    - checkout: self
      path: 'project'

    - checkout: 'templates'
      path: 'templates'

    - ${{ each target in parameters.target_frameworks }}:
      - task: UseDotNet@2
        displayName: 'Installing .Net Core SDK'
        inputs:
          packageType: 'sdk'
          version: ${{ target }}

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(Pipeline.Workspace)/project/${{parameters.projects}}'
        arguments: '--no-incremental --no-restore --configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: pack
        packagesToPack: '$(Pipeline.Workspace)/project/${{parameters.projects}}'
        configurationToPack: 'Release'
        versioningScheme: byEnvVar
        versionEnvVar: version
        outputDir: '$(Build.ArtifactStagingDirectory)'
        includesymbols: true

    - task: PublishPipelineArtifact@1
      displayName: Store Application Artifact
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'
        artifact: '${{parameters.artifact_name}}'

- ${{ if eq(parameters.run_sonar, true) }}:
  - stage: run_sonar
    displayName: 'Run Sonar'
    pool:
      name: ${{parameters.pool}}
    dependsOn: ${{parameters.depends_on}}
    jobs:
      - job: sonar
        displayName: 'Sonar'
        condition: succeeded()
        variables:
          version: ${{parameters.version}}
        steps:
          - checkout: self
            path: 'project'
          - checkout: 'templates'
            path: 'templates'

          - task: SonarCloudPrepare@3
            inputs:
              SonarQube: ${{parameters.sonar_service}}
              organization: ${{parameters.sonar_organization}}
              scannerMode: 'dotnet'
              projectKey: ${{parameters.sonar_project_key}}
              projectVersion: '${{parameters.version}}'
              extraProperties: |
                # Additional properties that will be passed to the scanner, 
                # Put one key=value per line, example:
                sonar.exclusions=**/*test*
                sonar.exclusions=**/lib/**
                sonar.coverageReportPaths=$(Pipeline.Workspace)/project/Reports_Coverage/SonarQube.xml

          - ${{ each target in parameters.target_frameworks }}:
            - task: UseDotNet@2
              displayName: 'Installing .Net Core SDK'
              inputs:
                packageType: 'sdk'
                version: ${{ target }}

          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '$(Pipeline.Workspace)/project/*.sln'

          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: '$(Pipeline.Workspace)/project'
              arguments: '--no-incremental --no-restore --configuration Release'

          - ${{ if eq(parameters.run_tests, true) }}:
              - task: DotNetCoreCLI@2
                displayName: Install ReportGenerator Global Tool
                inputs:
                  command: custom
                  custom: tool
                  arguments: update dotnet-reportgenerator-globaltool --tool-path tools --ignore-failed-sources

              - bash: |
                  ls $(Pipeline.Workspace)/project/test*/**/*.csproj | xargs -L1 dotnet test --collect:"XPlat Code Coverage" --settings $COVERLET_PATH --logger trx
                displayName: Test
                env:
                  COVERLET_PATH: '$(Pipeline.Workspace)/templates/coverlet/coverlet.runsettings'

              - bash: |
                  ./tools/reportgenerator "-reports:$(Pipeline.Workspace)/project/test*/*/TestResults/*/coverage.cobertura.xml" "-targetdir:$(Pipeline.Workspace)/project/Reports_Coverage" -reportTypes:"Cobertura;SonarQube";
                displayName: Generate code coverage report

              - task: PublishTestResults@2
                inputs:
                  testResultsFormat: 'VSTest'
                  testResultsFiles: '$(Pipeline.Workspace)/project/**/*.trx'
                  mergeTestResults: true
                displayName: Publish test result

              - task: PublishCodeCoverageResults@1
                inputs:
                  codeCoverageTool: 'Cobertura'
                  summaryFileLocation: $(Pipeline.Workspace)/project/Reports_Coverage/Cobertura.xml
                  pathToSources: $(Pipeline.Workspace)/project/src/
                displayName: Publish coverage

          - task: SonarCloudAnalyze@3
            displayName: 'Run Code Analysis'
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'

          - task: SonarCloudPublish@3
            displayName: 'Publish Quality Gate Result'
            inputs:
              pollingTimeoutSec: '300'
          