ARG DLL_NAME
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY . .

#NEWRELIC INSTALL
RUN apt-get update && apt-get install -y wget ca-certificates gnupg \
&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
&& wget https://download.newrelic.com/548C16BF.gpg \
&& apt-key add 548C16BF.gpg \
&& apt-get update \
&& apt-get install -y newrelic-netcore20-agent \
&& rm -rf /var/lib/apt/lists/*

ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so

##NEWRELIC INSTALL

#TIMEZONE INSTALL

RUN apt-get install -y tzdata

#TIMEZONE INSTALL

ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "$DLL_NAME.dll"]