FROM mcr.microsoft.com/dotnet/aspnet:#{IMAGE_VERSION}#-alpine
WORKDIR /app
EXPOSE 80

COPY . .

ENV ASPNETCORE_HTTP_PORTS=80
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "#{DLL_NAME}#"]