ARG DLL_NAME
ARG IMAGE_VERSION
FROM mcr.microsoft.com/dotnet/aspnet:${IMAGE_VERSION}
WORKDIR /app
EXPOSE 80

COPY . .

ENV ASPNETCORE_HTTP_PORTS=80
ENV ASPNETCORE_ENVIRONMENT=Production
ENV DLL_NAME=${DLL_NAME}

ENTRYPOINT ["dotnet", "$DLL_NAME"]