parameters:
- name: artifact_name
  type: string
  default: 'artifact'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - build
- name: environments
  type: object
  default: 
  - Production
- name: target_frameworks
  type: object
  default:
  - net6.0
- name: image_name
  type: string
- name: dll_name
  type: string

stages:
- stage: image_deploy
  displayName: 'Image Deploy'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  condition: succeeded()
  jobs:
  - ${{ each environment in parameters.environments }}:
    - deployment: image_deployment_${{environment}}
      environment: ${{environment}}
      workspace:
        clean: all
      variables:
        dll_name: ${{ parameters.dll_name }}
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: 'templates'
              path: 'templates'

            - task: Docker@2
              inputs:
                containerRegistry: 'digital_ocean'
                repository: ${{ parameters.image_name }}
                command: 'build'
                Dockerfile: '$(Pipeline.Workspace)/templates/Dockerfiles/Dockerfile'
                buildContext: $(Pipeline.Workspace)/${{parameters.artifact_name}}
                tags: '$(Build.BuildNumber)'
                arguments: --build-arg DLL_NAME=${{ parameters.dll_name }}
                addPipelineData: false
                addBaseImageData: false