parameters:
- name: artifact_name
  type: string
  default: 'library'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - library_build
- name: environments
  type: object
  default: 
  - Production
- name: target_frameworks
  type: object
  default:
  - net6.0
- name: nuget_api_key
  type: string
  default: $(NUGET_API_KEY)

stages:
- stage: library_deploy
  displayName: 'Library Deploy'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  condition: succeeded()
  jobs:
  - ${{ each environment in parameters.environments }}:
    - deployment: library_deployment_${{environment}}
      environment: ${{environment}}
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: |
                dotnet push $(Pipeline.Workspace)/${{parameters.artifact_name}}/!(*symbols).nupkg -k ${{ parameters.nuget_api_key }}
              displayName: 'Push to Nuget'
              name: nuget_push