parameters:
- name: artifact_name
  type: string
  default: 'library'
- name: pool
  type: string
  default: 'Azure Pipelines'
  values:
  - 'Azure Pipelines'
  - 'Self-hosted'
- name: depends_on
  type: object
  default:
  - library_build
- name: environments
  type: object
  default: 
  - Production
- name: target_frameworks
  type: object
  default:
  - net6.0
- name: feed
  type: string
  default: '68e046c8-6357-4886-b971-0b7324cc4148'

stages:
- stage: library_deploy
  displayName: 'Library Deploy'
  pool:
    name: ${{parameters.pool}}
  dependsOn: ${{parameters.depends_on}}
  condition: succeeded()
  jobs:
  - ${{ each environment in parameters.environments }}:
    - deployment: library_deployment_${{environment}}
      environment: ${{environment}}
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DotNetCoreCLI@2
              displayName: 'Push to Nuget'
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/!(*symbols).nupkg'
                publishPackageMetadata: false
                includesymbols: true
                feedsToUse: 'select'
                vstsFeed: ${{parameters.feed}}