parameters:
  - name: name
    type: string
  - name: display_name
    type: string
  - name: user_email
    type: string
  - name: user_name
    type: string

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{parameters.display_name}}
    condition: succeeded()
    steps:
      - checkout: self
        path: 'project'
        persistCredentials: true
      
      - checkout: 'templates'
        path: 'templates'

      - task: DownloadPipelineArtifact@2
        name: download_artifact
        displayName: 'Download artifact'
        inputs:
          path: $(Pipeline.Workspace)

      - task: Bash@3
        name: extract_artifact
        displayName: 'Extract artifacts'
        inputs:
          filePath: '$(Pipeline.Workspace)/templates/azure/scripts/extract_files.sh'
        env:
          SOURCE_PATH: '$(Pipeline.Workspace)/**/*.zip'
          DESTINATION_PATH: '$(Pipeline.Workspace)/deploy'

      - task: Bash@3
        name: update_version
        displayName: 'Update version'
        inputs:
          filePath: '$(Pipeline.Workspace)/templates/azure/scripts/update_version.sh'
        env:
          SOURCE_BRANCH: $(Build.SourceBranchName)
          SOURCE_PATH: $(Pipeline.Workspace)/project
          ARTIFACT_PATH: $(Pipeline.Workspace)/deploy
          USER_EMAIL: ${{ parameters.user_email }}
          USER_NAME: ${{ parameters.user_name }}