parameters:
  - name: name
    type: string
  - name: display_name
    type: string
  - name: dll_name
    type: string
  - name: artifact_name
    type: string
  - name: condition
    type: boolean
    default: true
  - name: project_path
    type: string
  - name: user_email
    type: string
  - name: user_name
    type: string

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{parameters.display_name}}
    variables:
      dll_path: $(Pipeline.Workspace)/${{parameters.artifact_name}}/deploy/${{parameters.dll_name}}
    steps:
      - checkout: self
        path: 'project'
        persistCredentials: true
      
      - checkout: 'templates'
        path: 'templates'

      - task: DownloadPipelineArtifact@2
        name: download_artifact
        displayName: 'Download artifact'
        inputs:
          artifact: ${{parameters.artifact_name}}
          path: $(Pipeline.Workspace)/${{parameters.artifact_name}}

      - task: ExtractFiles@1
        name: extract_artifact
        displayName: 'Extract artifact'
        inputs:
          archiveFilePatterns: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/**/*.zip'
          destinationFolder: '$(Pipeline.Workspace)/${{parameters.artifact_name}}/deploy'
          cleanDestinationFolder: true
          overwriteExistingFiles: true

      - template: /azure/steps/version/get.yml@templates
        parameters:
          dll_path: $(dll_path)

      - task: Bash@3
        name: update_version
        displayName: 'Update version'
        inputs:
          filePath: '$(Pipeline.Workspace)/templates/azure/scripts/update_version.sh'
        env:
          DLL_PATH: $(dll_path)
          PROJECT_PATH: ${{ parameters.project_path }}
          USER_EMAIL: ${{ parameters.user_email }}
          USER_NAME: ${{ parameters.user_name }}